import type { FundData } from '@/types/fund'

export const sampleFunds: FundData[] = [
  {
    id: 'sample-1',
    fundName: 'Global Equity Growth Fund',
    fund_factsheet_as_of_date: '2024-12-31',
    launchDate: '2019-03-15',
    investmentObjective: 'To achieve long-term capital appreciation by investing primarily in equity securities of companies with strong growth potential across global markets.',
    riskLevel: 'High',
    returns: {
      oneYearAnnualized: 18.45,
      threeYearAnnualized: 12.32,
      fiveYearAnnualized: 15.67,
      sinceLaunchAnnualized: 14.23,
      calendarYear2024: 19.12,
      calendarYear2023: 16.89,
      calendarYear2022: -8.45,
    },
    assetClasses: [
      { class: 'Equities - US', allocationPercent: 45.2 },
      { class: 'Equities - International Developed', allocationPercent: 28.5 },
      { class: 'Equities - Emerging Markets', allocationPercent: 15.3 },
      { class: 'Fixed Income', allocationPercent: 8.0 },
      { class: 'Cash & Equivalents', allocationPercent: 3.0 },
    ],
    top10Holdings: [
      { name: 'Apple Inc.', allocationPercent: 8.5 },
      { name: 'Microsoft Corporation', allocationPercent: 7.2 },
      { name: 'Amazon.com Inc.', allocationPercent: 6.8 },
      { name: 'Alphabet Inc. Class A', allocationPercent: 5.9 },
      { name: 'NVIDIA Corporation', allocationPercent: 5.4 },
      { name: 'Tesla Inc.', allocationPercent: 4.7 },
      { name: 'Meta Platforms Inc.', allocationPercent: 4.2 },
      { name: 'Taiwan Semiconductor', allocationPercent: 3.8 },
      { name: 'ASML Holding NV', allocationPercent: 3.5 },
      { name: 'Visa Inc.', allocationPercent: 3.2 },
    ],
    sourceFile: 'sample-factsheet-1.jpg',
    processedAt: new Date().toISOString(),
  },
  {
    id: 'sample-2',
    fundName: 'Balanced Income Fund',
    fund_factsheet_as_of_date: '2024-12-31',
    launchDate: '2017-06-20',
    investmentObjective: 'To provide a balance of income and capital appreciation through a diversified portfolio of equities and fixed income securities.',
    riskLevel: 'Medium',
    returns: {
      oneYearAnnualized: 8.92,
      threeYearAnnualized: 6.45,
      fiveYearAnnualized: 7.23,
      sinceLaunchAnnualized: 6.89,
      calendarYear2024: 9.15,
      calendarYear2023: 7.32,
      calendarYear2022: -3.21,
    },
    assetClasses: [
      { class: 'Fixed Income - Corporate', allocationPercent: 40.0 },
      { class: 'Equities - US', allocationPercent: 35.0 },
      { class: 'Fixed Income - Government', allocationPercent: 15.0 },
      { class: 'Equities - International', allocationPercent: 7.5 },
      { class: 'Cash & Equivalents', allocationPercent: 2.5 },
    ],
    top10Holdings: [
      { name: 'US Treasury 10Y', allocationPercent: 12.5 },
      { name: 'Apple Inc.', allocationPercent: 6.8 },
      { name: 'Microsoft Corporation', allocationPercent: 5.9 },
      { name: 'Corporate Bond ETF', allocationPercent: 5.2 },
      { name: 'Johnson & Johnson', allocationPercent: 4.5 },
      { name: 'Procter & Gamble', allocationPercent: 4.1 },
      { name: 'Coca-Cola Company', allocationPercent: 3.8 },
      { name: 'JPMorgan Chase & Co.', allocationPercent: 3.5 },
      { name: 'Bank of America Corp', allocationPercent: 3.2 },
      { name: 'Wells Fargo & Company', allocationPercent: 2.9 },
    ],
    sourceFile: 'sample-factsheet-2.jpg',
    processedAt: new Date().toISOString(),
  },
  {
    id: 'sample-3',
    fundName: 'Technology Innovation Fund',
    fund_factsheet_as_of_date: '2024-12-31',
    launchDate: '2020-01-10',
    investmentObjective: 'To capitalize on technological innovation by investing in companies at the forefront of technological advancement, including AI, cloud computing, and digital transformation.',
    riskLevel: 'Very High',
    returns: {
      oneYearAnnualized: 32.67,
      threeYearAnnualized: 24.89,
      fiveYearAnnualized: 28.45,
      sinceLaunchAnnualized: 26.12,
      calendarYear2024: 35.23,
      calendarYear2023: 28.67,
      calendarYear2022: -12.34,
    },
    assetClasses: [
      { class: 'Equities - Technology', allocationPercent: 75.0 },
      { class: 'Equities - Communication Services', allocationPercent: 15.0 },
      { class: 'Equities - Healthcare Technology', allocationPercent: 7.0 },
      { class: 'Cash & Equivalents', allocationPercent: 3.0 },
    ],
    top10Holdings: [
      { name: 'NVIDIA Corporation', allocationPercent: 12.5 },
      { name: 'Microsoft Corporation', allocationPercent: 11.2 },
      { name: 'Apple Inc.', allocationPercent: 10.8 },
      { name: 'Alphabet Inc. Class A', allocationPercent: 9.5 },
      { name: 'Amazon.com Inc.', allocationPercent: 8.9 },
      { name: 'Meta Platforms Inc.', allocationPercent: 7.2 },
      { name: 'Advanced Micro Devices', allocationPercent: 6.5 },
      { name: 'Broadcom Inc.', allocationPercent: 5.8 },
      { name: 'Oracle Corporation', allocationPercent: 5.2 },
      { name: 'Salesforce Inc.', allocationPercent: 4.6 },
    ],
    sourceFile: 'sample-factsheet-3.jpg',
    processedAt: new Date().toISOString(),
  },
  {
    id: 'sample-4',
    fundName: 'Emerging Markets Fund',
    fund_factsheet_as_of_date: '2024-12-31',
    launchDate: '2018-09-05',
    investmentObjective: 'To achieve long-term capital growth by investing primarily in equity securities of companies located in emerging market countries.',
    riskLevel: 'High',
    returns: {
      oneYearAnnualized: 15.23,
      threeYearAnnualized: 8.45,
      fiveYearAnnualized: 10.12,
      sinceLaunchAnnualized: 9.67,
      calendarYear2024: 16.89,
      calendarYear2023: 12.34,
      calendarYear2022: -15.67,
    },
    assetClasses: [
      { class: 'Equities - China', allocationPercent: 30.0 },
      { class: 'Equities - India', allocationPercent: 25.0 },
      { class: 'Equities - Brazil', allocationPercent: 15.0 },
      { class: 'Equities - South Korea', allocationPercent: 12.0 },
      { class: 'Equities - Taiwan', allocationPercent: 10.0 },
      { class: 'Equities - Other Emerging Markets', allocationPercent: 6.0 },
      { class: 'Cash & Equivalents', allocationPercent: 2.0 },
    ],
    top10Holdings: [
      { name: 'Taiwan Semiconductor', allocationPercent: 8.5 },
      { name: 'Tencent Holdings Ltd', allocationPercent: 7.2 },
      { name: 'Samsung Electronics', allocationPercent: 6.8 },
      { name: 'Alibaba Group Holding', allocationPercent: 6.2 },
      { name: 'Reliance Industries', allocationPercent: 5.5 },
      { name: 'Infosys Ltd', allocationPercent: 4.9 },
      { name: 'Vale SA', allocationPercent: 4.3 },
      { name: 'Petrobras', allocationPercent: 3.8 },
      { name: 'SK Hynix Inc', allocationPercent: 3.5 },
      { name: 'Meituan', allocationPercent: 3.2 },
    ],
    sourceFile: 'sample-factsheet-4.jpg',
    processedAt: new Date().toISOString(),
  },
]


